version: '3.3'

services:
  web:
    build:
      context: .
    image: mado96/hsrt-webshop:latest
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    restart: always

  # mssql:
  #   image: mcr.microsoft.com/mssql/server:2022-latest
  #   container_name: sqlserver
  #   ports:
  #     - "1433:1433" 
  #   environment:
  #     - ACCEPT_EULA=Y
  #     - SA_PASSWORD=YourStrong!Passw0rd
  #     - MSSQL_PID=Express 
  #   volumes:
  #     - mssql_data:/var/opt/mssql 
  #   restart: always

networks:
  default:
    driver: bridge

# volumes:
#   mssql_data:
#     driver: local
